### ISSUE TITLE
Fram gather support

### ISSUE THREAD

**Issue by KrychunIvan** [Ennui-Ninja/Albion-Script-API#6]
Do you plan to expand the api? I tried to write some small script to gather farm, FastTravel by players name work fine, but when i try to understand how to gather farmble object i find white space in API, for example now i cant to pickup the crop.

# Key issues:

1. IFarmableWindow does not have semantics of the interface.
    1.1 IFarmableWindow must be the heir of IWidget.
    1.2 IFarmableWindow shoull have IFarmableObject object like ILootWindow has ILootObject.

2. IFarmableObject shoull have IItemContainerProxy object to feed animals.

**Comment by demmonic** [comment]
I'm working on this as we speak. I'll post an update when available.

**Comment by demmonic** [comment]
[https://github.com/Ennui-Ninja/Albion-Script-API/commit/3ed0f98fc6986a32e4b766662071e6c6b1982aff](https://github.com/Ennui-Ninja/Albion-Script-API/commit/3ed0f98fc6986a32e4b766662071e6c6b1982aff)

It's not exactly what you wanted, but all functionality is available. You'll be able to use the new API once it moves out of the nightly branch.
